// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __sendFunc_hh__
#define __sendFunc_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_sendFunc
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_sendFunc
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_sendFunc
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



#ifndef __sendToServer__
#define __sendToServer__
class sendToServer;
class _objref_sendToServer;
class _impl_sendToServer;

typedef _objref_sendToServer* sendToServer_ptr;
typedef sendToServer_ptr sendToServerRef;

class sendToServer_Helper {
public:
  typedef sendToServer_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_sendToServer, sendToServer_Helper> sendToServer_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_sendToServer,sendToServer_Helper > sendToServer_out;

#endif

// interface sendToServer
class sendToServer {
public:
  // Declarations for this interface type.
  typedef sendToServer_ptr _ptr_type;
  typedef sendToServer_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
  
  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static inline _ptr_type _fromObjRef(omniObjRef* o) {
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.
  
};

class _objref_sendToServer :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  // IDL operations
  ::CORBA::Char sendCharToServer(::CORBA::Char character);

  // Constructors
  inline _objref_sendToServer()  { _PR_setobj(0); }  // nil
  _objref_sendToServer(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_sendToServer();

  
private:
  virtual void* _ptrToObjRef(const char*);

  _objref_sendToServer(const _objref_sendToServer&);
  _objref_sendToServer& operator = (const _objref_sendToServer&);
  // not implemented

  friend class sendToServer;
};

class _pof_sendToServer : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_sendToServer() : _OMNI_NS(proxyObjectFactory)(sendToServer::_PD_repoId) {}
  virtual ~_pof_sendToServer();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_sendToServer :
  public virtual omniServant
{
public:
  virtual ~_impl_sendToServer();

  virtual ::CORBA::Char sendCharToServer(::CORBA::Char character) = 0;
  
public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();
  
};




class POA_sendToServer :
  public virtual _impl_sendToServer,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_sendToServer();

  inline ::sendToServer_ptr _this() {
    return (::sendToServer_ptr) _do_this(::sendToServer::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr



inline void
sendToServer::_marshalObjRef(::sendToServer_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_sendFunc
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_sendFunc
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_sendFunc
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_sendFunc
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_sendFunc
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_sendFunc
#endif

#endif  // __sendFunc_hh__

